### ISSUE TITLE
Those Nights, 44, 10, 16, Hallelujah

### ISSUE THREAD

**Issue by KyleSanderson** [aav7fl/website#46]
Somehow wound up on these old albums that don't really exist anymore. Are you still making music man? Any other Volumes/Albums? Always enjoyed the piano but I know the other fellow involved stopped mastering... god. what feels like over 7 years ago easily now.

**Comment by aav7fl** [comment]
Hey, I'm glad you still enjoy those tracks! It's been a long time.

I haven't written any new music in while. Most of my projects have been centered more automation and computers. But I do see that you're missing two songs from you list.

- [#12](https://kyleniewiada.bandcamp.com/track/12)
- [#32](https://kyleniewiada.bandcamp.com/track/32)

They're uh.. interesting to listen to after all of these years 😆. 

I've got a handful of other unreleased covers and songs from 2008-2013. I'll see what I can do about getting them up somewhere in the near future.

**Comment by aav7fl** [comment]
@KyleSanderson Sorry for the break. I've got one last one from my archives that seems to a finished work. It's a cover of [Love Drunk - Boys Like Girls](https://www.youtube.com/watch?v=o0c-kC8xZ-I).

[Love Drunk - Ambient.zip](https://github.com/aav7fl/website/files/4808705/Love.Drunk.-.Ambient.zip)
